<a href="https://colab.research.google.com/github/amrutha-m-sajeev/Machine-learning/blob/main/cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/cancer patient data sets.csv')
df

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,P995,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
996,996,P996,37,2,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
997,997,P997,25,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
998,998,P998,18,2,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
999,999,P999,47,1,6,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High

In [28]:
df.head()

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,Low
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,Medium
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,High
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High

In [29]:
df.tail()

,index,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
995,995,P995,44,1,6,7,7,7,7,6,...,5,3,2,7,8,2,4,5,3,High
996,996,P996,37,2,6,8,7,7,7,6,...,9,6,5,7,2,4,3,1,4,High
997,997,P997,25,2,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High
998,998,P998,18,2,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,High
999,999,P999,47,1,6,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,High

In [30]:
df.columns

Index(['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'OccuPational Hazards', 'Genetic Risk',
       'chronic Lung Disease', 'Balanced Diet', 'Obesity', 'Smoking',
       'Passive Smoker', 'Chest Pain', 'Coughing of Blood', 'Fatigue',
       'Weight Loss', 'Shortness of Breath', 'Wheezing',
       'Swallowing Difficulty', 'Clubbing of Finger Nails', 'Frequent Cold',
       'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [31]:
df.drop(['index','Patient Id'],axis='columns',inplace=True)
df

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,33,1,2,4,5,4,3,2,2,4,...,3,4,2,2,3,1,2,3,4,Low
1,17,1,3,1,5,3,4,2,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,35,1,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
3,37,1,7,7,7,7,6,7,7,7,...,4,2,3,1,4,5,6,7,5,High
4,46,1,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,6,7,7,7,7,6,7,7,...,5,3,2,7,8,2,4,5,3,High
996,37,2,6,8,7,7,7,6,7,7,...,9,6,5,7,2,4,3,1,4,High
997,25,2,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High
998,18,2,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,High
999,47,1,6,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,High

In [32]:
df.isna().sum()

Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1000 non-null   int64
 1   Gender                    1000 non-null   int64
 2   Air Pollution             1000 non-null   int64
 3   Alcohol use               1000 non-null   int64
 4   Dust Allergy              1000 non-null   int64
 5   OccuPational Hazards      1000 non-null   int64
 6   Genetic Risk              1000 non-null   int64
 7   chronic Lung Disease      1000 non-null   int64
 8   Balanced Diet             1000 non-null   int64
 9   Obesity                   1000 non-null   int64
 10  Smoking                   1000 non-null   int64
 11  Passive Smoker            1000 non-null   int64
 12  Chest Pain                1000 non-null   int64
 13  Coughing of Blood         1000 non-null   int64
 14  Fatigue                   1000 non-null   int64
 15  Weight Loss               1000 non-null   int64
 16  Shortness of Breath       1000 non-null   int64
 17  Wheezing                  1000 non-null   int64
 18  Swallowing Difficulty     1000 non-null   int64
 19  Clubbing of Finger Nails  1000 non-null   int64
 20  Frequent Cold             1000 non-null   int64
 21  Dry Cough                 1000 non-null   int64
 22  Snoring                   1000 non-null   int64
 23  Level                     1000 non-null   object
dtypes: int64(23), object(1)
memory usage: 187.6+ KB

In [34]:
x=df.iloc[:,:-1].values
x

array([[33,  1,  2, ...,  2,  3,  4],
       [17,  1,  3, ...,  1,  7,  2],
       [35,  1,  4, ...,  6,  7,  2],
       ...,
       [25,  2,  4, ...,  6,  7,  2],
       [18,  2,  6, ...,  4,  2,  3],
       [47,  1,  6, ...,  6,  7,  2]])

In [35]:
y=df.iloc[:,-1]
y

0         Low
1      Medium
2        High
3        High
4        High
        ...
995      High
996      High
997      High
998      High
999      High
Name: Level, Length: 1000, dtype: object

In [36]:
x.ndim

2

In [37]:
y.ndim

1

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

array([[25,  2,  3, ...,  5,  1,  1],
       [38,  1,  2, ...,  3,  2,  2],
       [29,  2,  4, ...,  6,  7,  2],
       ...,
       [27,  1,  2, ...,  2,  1,  5],
       [44,  1,  6, ...,  4,  5,  3],
       [37,  2,  7, ...,  6,  7,  5]])

In [39]:
x_test

array([[32,  1,  1, ...,  7,  7,  5],
       [38,  2,  6, ...,  3,  4,  2],
       [26,  1,  3, ...,  6,  5,  4],
       ...,
       [35,  1,  4, ...,  6,  7,  2],
       [34,  1,  6, ...,  6,  7,  5],
       [52,  1,  3, ...,  2,  3,  3]])

In [40]:
y_test

957    Medium
286    Medium
983    Medium
940       Low
244      High
        ...
86     Medium
939       Low
227      High
905      High
389       Low
Name: Level, Length: 300, dtype: object

In [41]:
y_train

382       Low
392       Low
987      High
694      High
895       Low
        ...
12     Medium
743    Medium
675    Medium
107      High
901      High
Name: Level, Length: 700, dtype: object

In [42]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
x_train

array([[-0.99931404,  1.20670641, -0.42839994, ...,  0.81330742,
        -1.37910361, -1.28469055],
       [ 0.08598943, -0.82870199, -0.92000643, ..., -0.28894852,
        -0.89104874, -0.61558089],
       [-0.66537451,  1.20670641,  0.06320655, ...,  1.36443539,
         1.5492256 , -0.61558089],
       ...,
       [-0.83234428, -0.82870199, -0.92000643, ..., -0.84007649,
        -1.37910361,  1.39174809],
       [ 0.58689872, -0.82870199,  1.04641953, ...,  0.26217945,
         0.57311586,  0.05352877],
       [ 0.00250455,  1.20670641,  1.53802602, ...,  1.36443539,
         1.5492256 ,  1.39174809]])

In [43]:
x_test

array([[-0.46944309, -0.79959006, -1.37213514, ...,  1.83715349,
         1.53343589,  1.44593153],
       [ 0.02908055,  1.25064086,  1.10762716, ..., -0.30114349,
         0.04144421, -0.659794  ],
       [-0.96796673, -0.79959006, -0.38023022, ...,  1.30257925,
         0.53877477,  0.74402302],
       ...,
       [-0.22018127, -0.79959006,  0.11572224, ...,  1.30257925,
         1.53343589, -0.659794  ],
       [-0.30326855, -0.79959006,  1.10762716, ...,  1.30257925,
         1.53343589,  1.44593153],
       [ 1.19230236, -0.79959006, -0.38023022, ..., -0.83571774,
        -0.45588635,  0.04211451]])

In [44]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Medium', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'High',
       'Medium', 'Medium', 'Low', 'Medium', 'High', 'Medium', 'Low',
       'Medium', 'Medium', 'Low', 'High', 'Low', 'Low', 'Medium',
       'Medium', 'High', 'Low', 'Low', 'High', 'High', 'Medium', 'High',
       'Low', 'High', 'High', 'Medium', 'Medium', 'High', 'Low', 'High',
       'Medium', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'Low',
       'High', 'Medium', 'High', 'Medium', 'Medium', 'Low', 'Medium',
       'High', 'Low', 'High', 'Medium', 'High', 'High', 'Medium', 'Low',
       'Low', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Medium',
       'Medium', 'High', 'Low', 'Medium', 'Medium', 'Medium', 'High',
       'High', 'High', 'Medium', 'Medium', 'Low', 'High', 'Medium',
       'High', 'High', 'Low', 'Low', 'Low', 'High', 'High', 'Medium',
       'Medium', 'Medium', 'High', 'Low', 'Low', 'Medium', 'Low', 'High',
       'Medium', 'Low', 'Low', 'Medium', 'Medium', 'High', 'Medium',
       'Medium', 'High', 'Medium', 'Low', 'High', 'Low', 'High', 'High',
       'Medium', 'Low', 'High', 'Medium', 'Medium', 'Low', 'High',
       'Medium', 'Low', 'Medium', 'High', 'Medium', 'High', 'Medium',
       'High', 'High', 'Medium', 'Low', 'Medium', 'High', 'Medium',
       'Medium', 'Medium', 'Medium', 'High', 'Low', 'High', 'High', 'Low',
       'Low', 'High', 'High', 'Medium', 'High', 'Low', 'Low', 'Low',
       'Low', 'High', 'Low', 'Medium', 'Low', 'High', 'Low', 'Low', 'Low',
       'Medium', 'High', 'High', 'Medium', 'High', 'Low', 'Low', 'Medium',
       'Medium', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'High',
       'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Medium', 'Low',
       'Low', 'High', 'High', 'Low', 'High', 'Medium', 'Low', 'High',
       'Low', 'Low', 'High', 'Medium', 'High', 'Low', 'Low', 'Medium',
       'High', 'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Medium',
       'High', 'Low', 'Medium', 'High', 'High', 'High', 'Medium',
       'Medium', 'High', 'Medium', 'High', 'High', 'Medium', 'Low', 'Low',
       'High', 'Medium', 'Low', 'Low', 'High', 'High', 'Low', 'High',
       'Medium', 'Medium', 'Low', 'High', 'High', 'Medium', 'High',
       'Medium', 'High', 'Medium', 'Medium', 'Low', 'Medium', 'High',
       'Low', 'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'High', 'High',
       'Medium', 'Low', 'Medium', 'Low', 'Low', 'High', 'Medium', 'Low',
       'Low', 'Low', 'Medium', 'Low', 'High', 'Medium', 'Medium',
       'Medium', 'High', 'High', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'High', 'Low', 'Low', 'High', 'High', 'Medium',
       'Medium', 'High', 'Low', 'High', 'High', 'Medium', 'Low', 'High',
       'High', 'Low'], dtype=object)

In [45]:
y_pred

array(['Medium', 'Medium', 'Medium', 'Low', 'High', 'Medium', 'High',
       'Medium', 'Medium', 'Low', 'Medium', 'High', 'Medium', 'Low',
       'Medium', 'Medium', 'Low', 'High', 'Low', 'Low', 'Medium',
       'Medium', 'High', 'Low', 'Low', 'High', 'High', 'Medium', 'High',
       'Low', 'High', 'High', 'Medium', 'Medium', 'High', 'Low', 'High',
       'Medium', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'Low',
       'High', 'Medium', 'High', 'Medium', 'Medium', 'Low', 'Medium',
       'High', 'Low', 'High', 'Medium', 'High', 'High', 'Medium', 'Low',
       'Low', 'Medium', 'Medium', 'Medium', 'Medium', 'High', 'Medium',
       'Medium', 'High', 'Low', 'Medium', 'Medium', 'Medium', 'High',
       'High', 'High', 'Medium', 'Medium', 'Low', 'High', 'Medium',
       'High', 'High', 'Low', 'Low', 'Low', 'High', 'High', 'Medium',
       'Medium', 'Medium', 'High', 'Low', 'Low', 'Medium', 'Low', 'High',
       'Medium', 'Low', 'Low', 'Medium', 'Medium', 'High', 'Medium',
       'Medium', 'High', 'Medium', 'Low', 'High', 'Low', 'High', 'High',
       'Medium', 'Low', 'High', 'Medium', 'Medium', 'Low', 'High',
       'Medium', 'Low', 'Medium', 'High', 'Medium', 'High', 'Medium',
       'High', 'High', 'Medium', 'Low', 'Medium', 'High', 'Medium',
       'Medium', 'Medium', 'Medium', 'High', 'Low', 'High', 'High', 'Low',
       'Low', 'High', 'High', 'Medium', 'High', 'Low', 'Low', 'Low',
       'Low', 'High', 'Low', 'Medium', 'Low', 'High', 'Low', 'Low', 'Low',
       'Medium', 'High', 'High', 'Medium', 'High', 'Low', 'Low', 'Medium',
       'Medium', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'High',
       'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Medium', 'Low',
       'Low', 'High', 'High', 'Low', 'High', 'Medium', 'Low', 'High',
       'Low', 'Low', 'High', 'Medium', 'High', 'Low', 'Low', 'Medium',
       'High', 'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Medium',
       'High', 'Low', 'Medium', 'High', 'High', 'High', 'Medium',
       'Medium', 'High', 'Medium', 'High', 'High', 'Medium', 'Low', 'Low',
       'High', 'Medium', 'Low', 'Low', 'High', 'High', 'Low', 'High',
       'Medium', 'Medium', 'Low', 'High', 'High', 'Medium', 'High',
       'Medium', 'High', 'Medium', 'Medium', 'Low', 'Medium', 'High',
       'Low', 'Low', 'Medium', 'Low', 'High', 'High', 'Medium', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'High', 'High',
       'Medium', 'Low', 'Medium', 'Low', 'Low', 'High', 'Medium', 'Low',
       'Low', 'Low', 'Medium', 'Low', 'High', 'Medium', 'Medium',
       'Medium', 'High', 'High', 'Medium', 'Medium', 'Medium', 'Medium',
       'Medium', 'Medium', 'High', 'Low', 'Low', 'High', 'High', 'Medium',
       'Medium', 'High', 'Low', 'High', 'High', 'Medium', 'Low', 'High',
       'High', 'Low'], dtype=object)

In [46]:
pred=model.predict(scaler.transform([[20,2,4,5,2,1,8,5,9,7,5,9,5,3,2,1,3,5,2,1,3,6,2]]))
print(pred)

['Medium']

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
result

array([[106,   0,   0],
       [  0,  91,   0],
       [  0,   0, 103]])

In [48]:
score=accuracy_score(y_test,y_pred)
score

1.0